services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
    - "./mosquitto/config:/mosquitto/config"
    - "./mosquitto/log:/mosquitto/log"
    - "./mosquitto/data:/mosquitto/data"
    expose:
    - 1883
    ports:
    - 1883:1883 
    - 9001:9001
    hostname: mqtt

 